---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-stack
  namespace: argocd
spec:
  project: default 
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts
      chart: postgresql 
      targetRevision: 18.5.15
      helm:
        valueFiles: 
          - $values/postgresql/values.yaml
    - repoURL: https://github.com/PolarisKnight/homeops
      targetRevision: HEAD 
      ref: values 
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
