auth:
  postgresPassword: "changeme"
  username: "awx"
  password: "changeme"
  database: "awx"
  # existingSecret: ""
  # secretKeys:
  #   adminPasswordKey: ""
  #   userPasswordKey: ""
  #   replicationPasswordKey: ""

  service:
    type: LoadBalancer
    