---
apiVersion: v1 
kind: Namespace
metadata:
  name: media-servers

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: linuxserver/plex
        env:
        - name: TZ
          value: "America/Denver"
      ports:
      - containerPort: 32400
        protocol: TCP
      volumeMounts:
      - name: tv-shows
        mountPath: /tv 
      - name: movies
        mountPath: /movies
      - name: plex-config
        mountPath: /config
    volumes:
    - name: tv-shows
      persistentVolumeClaim:
        claimName: media
    - name: movies
      persistentVolumeClaim:
        claimName: media
    - name: plex-config
      persistentVolumeClaim:
        claimName: plex-config

---
apiVersion: v1 
kind: Service
metadata:
  name: plex
  namespace: media-servers
spec:
  selector:
    app: plex
  ports:
  - protocol: TCP
    port: 32400
    targetPort: 32400
  type: LoadBalancer
      
