---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: linuxserver/plex
        env:
        - name: TZ
          value: "America/Denver"
        - name: PLEX_CLAIM
          value: "claim-hJ1gQr72mk6gT3js_A_p"
        # PORTS and MOUNTS belong INSIDE the container list
        ports:
        - containerPort: 32400
          protocol: TCP
        volumeMounts:
        - name: media
          mountPath: /media
        - name: plex-config
          mountPath: /config
      # VOLUMES belongs under 'spec', aligned with 'containers'
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config

---
apiVersion: v1 
kind: Service
metadata:
  name: plex
  namespace: media-servers
spec:
  selector:
    app: plex
  ports:
  - protocol: TCP
    port: 32400
    targetPort: 32400
  type: LoadBalancer