---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media-servers
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1000Gi
    storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media-servers
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi 
    storageClassName: longhorn
