---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: fbMediaConfig
  namespace: media-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1GB
  storageClassName: longhorn



---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: filebrowser-media
  namespace: media-servers

spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: media
          mountPath: /srv
        - name: fb-media-config
          mountPath: /config
      volumes:
      - name: media 
        persistentVolumeClaim:
          claimName: media
      - name: fb-media-config
        persistentVolumeClaim:
          claimName: fbMediaConfig
---
apiVersion: v1 
kind: Service
metadata:
  name: filebrowser-media
  namespace: media-servers 
spec:
  selector:
    app: filebrowser 
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer

# apiVersion: networking.k8s.io/v1
        