---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: fb-media-config
  namespace: media-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1GB
  storageClassName: longhorn
