---

grafana:
  enabled: true
  adminPassword: "changeme"
  
prometheus:
  prometheusSpec:
    retention: 7d
  enabled: true

prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false

alertmanager:
  enabled: false