---

apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: linuxserver/homeassistant
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
        ports:
        - containerPort: 8123
          protocol: TCP
      volumes:
      - name: home-assistant-data
        persistentVolumeClaim:
          claimName: cloudops
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  selector:
    app: home-assistant 
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
    nodePort: 31823
  type: NodePort

