---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudops
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: longhorn