---
apiVersion: v1 
kind: persistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin 
  template:
    metadata:
      labels:
         app: jellyfin 
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        env:
         