---
apiVersion: v1 
kind: persistentVolumeClaim
metadata:
  name: unifi-pvc
  namespace: infra
  annotations: 
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: unifi-controller
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: infra
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: unifi-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      volumes:
      - name: unifi-config
        persistentVolumeClaim:
          claimName: unifi-pvc
      containers:
      - name: unifi-controller
        image: linuxserver/unifi-network-application
        resources:
          limits:
            memory: "4Gi"
            cpu: "2000m"
        ports:
        - containerPort: 8443 # web UI
          protocol: TCP 
        - containerPort: 8080 # device adoption
          protocol: TCP
        - containerPort: 3478 # STUN
          protocol: UDP
        - containerPort: 10001 # device discovery
          protocol: UDP
       
        volumeMounts:
          - name: unifi-config
            mountPath: /config
    
    
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
  namespace: infra
  labels:
    app.kubernetes.io/part-of: unifi-controller
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app: unifi-controller
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
  type: LoadBalancer


