---
apiVersion: v1
kind: Namespace
metadata:
  name: game-servers

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: game-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers: 
      - name: minecraft
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: "2G"
        ports:
        - containerPort: 25565
          protocol: TCP
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: game-servers
spec:
  selector:
    app: minecraft
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 25565
  type: LoadBalancer 
