---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
  namespace: game-servers 
spec:
  accessModes:
    - ReadWriteOnce
  resources:  
    requests:
      storage: 20Gi
  storageClassName: longhorn