AWX:

  enabled: true
  name: awx
  spec:
    admin_user: admin 


  postgres:
    enabled: true
    postgresqlDatabase: awx 
    postgresqlUsername: awx 
    postgresqlPassword: changeme 
    persistence:
      enabled: true
      size: 5Gi